from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Protocol

import torch
from torch import Tensor
from torch.distributed import ReduceOp
from torch.optim import Optimizer


class Compute[*ModelsTs](Protocol):
    @property
    def models(self) -> tuple[*ModelsTs]: ...
    @property
    def device(self) -> torch.device: ...
    @property
    def is_main_process(self) -> bool: ...

    def autocast(self) -> AbstractContextManager[object]: ...
    def no_sync(self) -> AbstractContextManager[object]: ...

    def zero_gradients(self, optimizers: Sequence[Optimizer]) -> None: ...
    def backward_pass(self, loss: Tensor) -> None: ...
    def step_optimizers(
        self, optimizers: Sequence[Optimizer], clipping: float
    ) -> bool: ...

    def synchronize(self) -> None: ...
    def train(self, enabled: bool = True) -> None: ...
    def reduce(
        self, tensor: Tensor, op: ReduceOp.RedOpType = ReduceOp.SUM
    ) -> Tensor: ...
